//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doga
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class havaEntities : DbContext
    {
        public havaEntities()
            : base("name=havaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Istasyonlar> Istasyonlar { get; set; }
        public virtual DbSet<KullaniciTbl> KullaniciTbl { get; set; }
        public virtual DbSet<Parametreler> Parametreler { get; set; }
        public virtual DbSet<Sehirler> Sehirler { get; set; }
        public virtual DbSet<Veriler> Veriler { get; set; }
    }
}
