//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doga
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametreler
    {
        public byte Id { get; set; }
        public string ParametreAdi { get; set; }
    }
}
