//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doga
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veriler
    {
        public string İstasyon { get; set; }
        public string Parametre { get; set; }
        public string Birim { get; set; }
        public Nullable<double> Min__Değer { get; set; }
        public Nullable<double> Max__Değer { get; set; }
        public Nullable<double> Ort__Değer { get; set; }
        public Nullable<double> Veri_Adeti { get; set; }
        public Nullable<double> Veri_Yüzdesi { get; set; }
        public Nullable<double> Standart_Sapma { get; set; }
        public Nullable<double> Toplam_Değer { get; set; }
        public Nullable<int> IstasyonId { get; set; }
        public Nullable<int> ParametreId { get; set; }
    }
}
